name: Build and deploy ASP.NET Core app to Azure Web App - buildxp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build
        run: dotnet build --configuration Release
        working-directory: backend/api

      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: backend/api

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: >-
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'buildxp'
          slot-name: 'Production'
          package: backend/api/publish

      - name: Logout do Azure
        run: az logout
        if: always()
